root: true
env:
  browser: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle:
    - error
    - always-multiline
  space-before-function-paren:
    - error
    - never
