root: true
env:
  browser: true
  es2015: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  arrow-parens:
    - error
    - as-needed
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle:
    - error
    - always-multiline
  prefer-arrow-callback: error
  space-before-function-paren:
    - error
    - never
