language: python
python:
  - "3.8"

before_install:
  - "sudo apt-get install npm"
  - "sudo npm -g install less"

install:
  - "pip install -r requirements.txt"
  - "python ./manage.py migrate --settings=nkdsu.settings_testing"
  - "python ./manage.py collectstatic --no-input --settings=nkdsu.settings_testing"
script:
  - "python ./manage.py test --settings=nkdsu.settings_testing"
